export default {
  slug: "investment",
  category: "saving",
  icon: "💹",
  cardTitle: "Investment Calculator",
  cardBlurb: "See what a lump sum plus monthly investing could grow to over time.",
  h1: "Investment Calculator",
  metaTitle: "Investment Calculator — Future Value & Growth Estimate | FigureWise",
  metaDescription:
    "Free investment calculator: estimate the future value of a lump sum plus monthly contributions. See projected growth and how much is your money vs. earnings.",
  intro:
    "See what a starting amount plus steady monthly investing could grow into over the years, and watch how much of that ending balance is your own money versus the earnings stacked on top.",
  affiliateGroup: "savings",

  inputs: [
    { id: "initial", label: "Initial investment", prefix: "$", default: 10000, min: 0, max: 5000000, step: 500 },
    { id: "monthly", label: "Monthly investment", prefix: "$", default: 300, min: 0, max: 50000, step: 50 },
    { id: "annualReturn", label: "Expected annual return", suffix: "%", default: 8, min: 0, max: 30, step: 0.1 },
    { id: "years", label: "Years invested", suffix: "yrs", default: 25, min: 1, max: 60, step: 1 },
  ],

  outputs: [
    { id: "endingBalance", label: "Ending balance", format: "currency0", primary: true },
    { id: "totalInvested", label: "Total you invested", format: "currency0" },
    { id: "totalEarnings", label: "Total earnings", format: "currency0" },
  ],

  breakdown: {
    title: "Your money vs. earnings",
    parts: [
      { outputId: "totalInvested", label: "Invested", color: "#1f8f5f" },
      { outputId: "totalEarnings", label: "Earnings", color: "#f6a52f" },
    ],
  },

  compute: function (v) {
    var initial = Math.max(0, v.initial || 0);
    var monthly = Math.max(0, v.monthly || 0);
    var years = Math.max(0, v.years || 0);
    var r = (v.annualReturn || 0) / 100 / 12;
    var n = Math.round(years * 12);
    var bal = initial;
    for (var i = 0; i < n; i++) { bal = bal * (1 + r) + monthly; }
    var totalInvested = initial + monthly * n;
    return { endingBalance: bal, totalInvested: totalInvested, totalEarnings: bal - totalInvested };
  },

  content: {
    howItWorks: `<p>This calculator projects the <strong>future value</strong> of money you invest — a one-time lump sum today plus an optional amount you add every month. Each month it applies your expected return and then layers in your latest contribution, so your balance builds on itself month after month.</p>
<p>The real story is in the split. Part of your ending balance is simply the cash you put in; the rest is <strong>earnings</strong> — growth generated by the market and by earlier earnings compounding on themselves. The longer you stay invested, the more that earnings slice tends to outgrow what you actually contributed.</p>`,
    formula: `<p>Your balance is rolled forward one month at a time. Each month the running balance earns the monthly return, then your monthly investment is added:</p>
<div class="formula">balance = balance × (1 + r) + monthly</div>
<p>Here <strong>r</strong> is your expected annual return divided by 12, and the step repeats for <strong>n</strong> = years × 12 months, starting from your initial investment. At the end, <strong>total invested</strong> = initial + (monthly × n), and <strong>total earnings</strong> = ending balance − total invested.</p>`,
    tips: `<ul>
<li><strong>Time does the heavy lifting.</strong> Stretch the years slider and watch the earnings slice balloon — starting a few years earlier often beats investing a larger amount later.</li>
<li><strong>Automate the monthly amount.</strong> Even a modest recurring contribution compounds hard over decades; try nudging the monthly figure up by $50 to see the difference.</li>
<li><strong>Be conservative with the return.</strong> Long-run stock market averages have hovered near 7–10% before inflation, but real years swing wildly. Test a lower rate to pressure-check your plan.</li>
<li><strong>Remember this is pre-tax and pre-inflation.</strong> Fees, taxes on gains, and rising prices all eat into the headline number, so treat the result as an optimistic ceiling.</li>
</ul>`,
  },

  faq: [
    {
      q: "How does this investment calculator estimate future value?",
      a: "It starts with your initial investment, then for every month it grows the balance by your expected annual return divided by 12 and adds your monthly contribution. After the full number of years, it reports the ending balance and separates it into what you invested versus what you earned.",
    },
    {
      q: "What annual return should I use?",
      a: "There's no guaranteed number — returns depend on what you invest in and the market. A broad stock index has historically averaged somewhere around 7–10% over long periods, but individual years can be sharply negative. Use a rate you're comfortable defending, and try a lower one to stay realistic.",
    },
    {
      q: "Does the calculator account for taxes and inflation?",
      a: "No. The result is a pre-tax, pre-inflation estimate, so the future dollars shown will have less buying power than the same amount today. It also excludes account fees and expense ratios, which can meaningfully reduce long-term growth.",
    },
    {
      q: "Why is so much of my ending balance earnings rather than contributions?",
      a: "That's compounding at work. Once your investment starts generating returns, those returns begin earning returns of their own, so over long horizons the growth can eventually dwarf the cash you personally put in.",
    },
  ],

  related: [
    { slug: "compound-interest", label: "Compound Interest Calculator" },
    { slug: "retirement", label: "Retirement Calculator" },
    { slug: "inflation", label: "Inflation Calculator" },
  ],
};
